# Generated by Django 5.0.6 on 2024-07-23 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
