# Generated by Django 5.0.6 on 2024-08-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Shipping Address"},
        ),
    ]
