# Generated by Django 5.0.6 on 2024-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_shippingaddress_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
